# Generated by Django 5.2.3 on 2026-05-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('piece', 'pièce')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.ingredient'),
        ),
    ]
