# Generated by Django 5.2.3 on 2026-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default="L'Héritage Gourmand", max_length=200)),
                ('contact_email', models.EmailField(default='contact@lheritage.fr', max_length=254)),
                ('phone_number', models.CharField(default='+33 1 23 45 67 89', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('online_orders_enabled', models.BooleanField(default=True)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('reservations_enabled', models.BooleanField(default=True)),
                ('auto_confirm_reservations', models.BooleanField(default=False)),
                ('max_reservation_people', models.PositiveIntegerField(default=10)),
                ('table_assignment_required', models.BooleanField(default=True)),
                ('auto_free_table_after_payment', models.BooleanField(default=True)),
                ('kitchen_screen_enabled', models.BooleanField(default=True)),
                ('notify_kitchen_new_order', models.BooleanField(default=True)),
                ('cash_payment_enabled', models.BooleanField(default=True)),
                ('card_payment_enabled', models.BooleanField(default=True)),
                ('online_payment_enabled', models.BooleanField(default=False)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_management_enabled', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('block_order_if_stock_low', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('activity_logs_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres restaurant',
                'verbose_name_plural': 'Paramètres restaurant',
            },
        ),
    ]
