# Generated by Django 5.2.3 on 2026-05-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_table_reservation_updated_at_and_more'),
        ('tables', '0002_alter_restauranttable_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.restauranttable'),
        ),
    ]
