# Generated by Django 5.2.3 on 2026-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('CLIENT', 'Client'), ('SERVEUR', 'Serveur'), ('CHEF', 'Chef cuisinier'), ('CAISSIER', 'Caissier'), ('MENAGE', 'Femme de ménage'), ('LIVREUR', 'Livreur')], db_index=True, default='CLIENT', max_length=20),
        ),
    ]
