# Generated by Django 5.2.3 on 2026-05-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('seats', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservée'), ('occupied', 'Occupée'), ('in_service', 'En service'), ('to_clean', 'À nettoyer'), ('out_of_service', 'Hors service')], default='available', max_length=30)),
                ('shape', models.CharField(choices=[('round', 'Ronde'), ('square', 'Carrée'), ('rect', 'Rectangulaire')], default='round', max_length=20)),
                ('position_x', models.PositiveIntegerField(default=50)),
                ('position_y', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='tables.tablezone')),
            ],
            options={
                'ordering': ['zone__ordering', 'number'],
                'unique_together': {('zone', 'number')},
            },
        ),
    ]
