# Generated by Django 5.2.3 on 2026-05-09 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='zone',
            field=models.CharField(choices=[('interieur', 'Intérieur'), ('terrasse', 'Terrasse'), ('vip', 'VIP'), ('famille', 'Famille'), ('bar', 'Bar')], max_length=30),
        ),
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ['zone', 'number']},
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='seats',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='position_x',
            new_name='pos_x',
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='position_y',
            new_name='pos_y',
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='name',
            field=models.CharField(default='Table', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservée'), ('occupied', 'Occupée'), ('needs_cleaning', 'À nettoyer'), ('out_of_service', 'Hors service')], default='available', max_length=30),
        ),
        migrations.DeleteModel(
            name='TableZone',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='shape',
        ),
    ]
