# Generated by Django 5.2.3 on 2026-05-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('stock', '0002_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('piece', 'pièce')], max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='menu.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_usages', to='stock.ingredient')),
            ],
        ),
    ]
