# Generated by Django 5.2.3 on 2026-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PREPARING', 'Préparation'), ('COOKING', 'Cuisson'), ('READY', 'Prête'), ('SERVED', 'Servie'), ('OUT_FOR_DELIVERY', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
