# Generated by Django 5.2.3 on 2026-05-15 11:37

import django.db.models.deletion
from django.db import migrations, models


def copy_dish_names(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')

    for item in OrderItem.objects.select_related('dish').all():
        if item.dish_id and item.dish and not item.dish_name:
            item.dish_name = item.dish.name
            item.save(update_fields=['dish_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dishingredient'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dish_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(copy_dish_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dish'),
        ),
    ]
